### ISSUE TITLE
Error in gitchangelog

### ISSUE THREAD

**Issue by SamitD** [vaab/gitchangelog#101]
Error: Exception while running 'gitchangelog':
  | Traceback (most recent call last):
  |   File "c:\program files\python37\lib\site-packages\gitchangelog\gitchangelog.py", line 615, in read
  |     raise StopIteration
  | StopIteration
  |
  | The above exception was the direct cause of the following exception:
  |
  | Traceback (most recent call last):
  |   File "c:\program files\python37\lib\site-packages\gitchangelog\gitchangelog.py", line 1963, in main
  |     log_encoding=log_encoding,
  |   File "c:\program files\python37\lib\site-packages\gitchangelog\gitchangelog.py", line 1649, in changelog
  |     first_version = next(versions)
  |   File "c:\program files\python37\lib\site-packages\gitchangelog\gitchangelog.py", line 1588, in versions_data_iter
  |     for commit in commits:
  |   File "c:\program files\python37\lib\site-packages\gitchangelog\gitchangelog.py", line 1234, in log
  |     for key in GIT_FORMAT_KEYS]))
  |   File "c:\program files\python37\lib\site-packages\gitchangelog\gitchangelog.py", line 1234, in <listcomp>
  |     for key in GIT_FORMAT_KEYS]))
  | RuntimeError: generator raised StopIteration

**Comment by SamitD** [comment]
python  version - 3.7.0b2
gitchangelog version - 3.0.3

**Comment by vaab** [comment]
Thanks for the report, this is due to python 3.7 enforcing PEP-0479 (https://www.python.org/dev/peps/pep-0479/). As a workaround, you can use any python version <3.7 ... I'll have a quick look at it, I'm expecting a quick an easy fix, I just need to find a compatible fix for other python version.

**Comment by SamitD** [comment]
Thanks a lot . Will be looking forward to the fix

**Comment by Link-** [comment]
Super! Is this gonna go into a release soon? You can't imagine how annoying it is to revert back to an earlier python release on macOS..

**Comment by nvgoldin** [comment]
:+1: 

Ran into the same issue, any updates here?

**Comment by nvgoldin** [comment]
Updating that using ```pip install git+https://github.com/vaab/gitchangelog.git@d72a0f099d45ff03be7017926ef73a1ef3f7cf90``` resolves the issue for me.

**Comment by vaab** [comment]
Sorry for the late answer here, but yes @nvgoldin, you are right, it is quite easy to install directly. I'm very busy these days, and will do my best to release this as soon as possible. Meanwhile, installing directly the release from the git commit should be used.
