### ISSUE TITLE
Add date to the commit history

### ISSUE THREAD

**Issue by zhongjingjogy** [vaab/gitchangelog#102]
Hi,

I would like to ask a overall basic question: How can I add the date information to the commit items listed by `gitchangelog` ?

Using the default setting and I got something like this,

* Commit message [author]

And I prefer something like this,

* [Date] Commit Message [author]

I wonder if there is something to do with the `git log`, and I really need some clues from your guys to proceed. Any help will be appreciated.

Wish you all the best, and have a nice day.

Jing

**Comment by zhongjingjogy** [comment]
I finally found that this an easy one. 

`git log --format="[%H at %cd %au] %s"`

It seems that `gitchangelog` provide more comprehensive functions. But in my case,  `git log` is just enough.

End

**Comment by vaab** [comment]
You should have a look to the templating mecanism in ``gitchangelog``. It is quite straightforward to add the date to it and format it to you taste. Of course, if ``git log`` is enough for you there are no good reason to use ``gitchangelog``.
