### ISSUE TITLE
pystache missing as dependency?

### ISSUE THREAD

**Issue by slhck** [vaab/gitchangelog#122]
I installed gitchangelog but when calling it, I received:

```
Required 'pystache' python module not found.
```

```
➜  pip3 install gitchangelog
Collecting gitchangelog
  Downloading https://files.pythonhosted.org/packages/9d/f9/554f9d1e2031a330148299b81ed7d6d5f1ef8969154384ca4ae8dd403b7a/gitchangelog-3.0.4-py2.py3-none-any.whl (54kB)
    100% |████████████████████████████████| 61kB 526kB/s
Installing collected packages: gitchangelog
Successfully installed gitchangelog-3.0.4

➜ gitchangelog
zsh: correct 'gitchangelog' to 'git-changelog' [nyae]? n
Required 'pystache' python module not found.
```

**Comment by LexiconCode** [comment]
I believe pystache is not the default engine. Therefore pystache not a required dependency.

Snippet from the readme. While it's not explicit and seems to be implied that it's optional.
> Mustache
> 
> The mustache output engine uses mustache templates.
> 
> The mustache templates are powered via pystache the python implementation of the mustache specifications. So mustache output engine will only be available if you have pystache module available in your python environment.

**Comment by slhck** [comment]
I see, apparently I inherited a file that used mustache layout.
