### ISSUE TITLE
Provide more lowlevel information to templates

### ISSUE THREAD

**Issue by vaab** [vaab/gitchangelog#18]
Some templating mecanism have full python capabilities (mako for instance), and providing an already limited and parsed output limit a lot their expressiveness. By staying compatible with standard python interface and simple objects (dict-like and list-like), it could be a good idea to give full blown git commit object for instance, where information could be added as the need for them would come.

Here are a few ideas of lowlevel information that we could want:
- all GitCommit attributes
- diff-stat (list of file modified)
- boolean for merge commit or not

We don't want to fill memory in really large git history, so this feature should come after some type of lazy evaluation is implemented (see #19).

**Comment by deimosfr** [comment]
+1
Git commit would be appreciate. Thanks for your work indeed !
