### ISSUE TITLE
Can I deactivate sectioning ?

### ISSUE THREAD

**Issue by vaab** [vaab/gitchangelog#21]
For some project, I'd like to deactivate sectioning ("new", "changes"...). I understand that I can do it with some work:
- changing regexp in ``.gitchangelog.rc`` so that all commit messages goes to one default section.
- providing my own template in mustache or mako that would avoid printing the section name.

This is not straightforward, and maybe disabling sectionning should be easier and supported by the default gitchangelog templates.

**Comment by kminh** [comment]
Is there an official way to override templates provided by this package?

**Comment by tuukkamustonen** [comment]
@kminh I recall I am doing it like this:

    section_regexps = [
        ('', None)
    ]

**Comment by tuukkamustonen** [comment]
The problem with my configuration is that while it disables the default sectioning, prefixes are still snipped away as per underlying rules. It seems like gitchangelog internally applies https://github.com/vaab/gitchangelog/blob/master/gitchangelog.rc.reference#L77 rules, even if user specifies his own `section_regexps`?

**Comment by vaab** [comment]
Yes, the defaults are the reference config file. You should really copy the whole reference file as a start if you want to change defaults. You can safely delete anything that you don't want to change. Your feedback catched my attention about this being unclear. Not sure yet how I'll tackle this (change needed, more doc needed ?). Feel free to suggest.

**Comment by tuukkamustonen** [comment]
@vaab Maybe just point out in the docs (or FAQ) that you can disable sectioning by:

    section_regexps = [
        ('', None)
    ]

However, without sectioning, user probably also wants to see the new/fix/chg prefixes in each commit, so the default behavior of removing those needs to be also removed by specifying:

    subject_process = (strip | ucfirst | final_dot)

**Comment by vaab** [comment]
Ok, do you think this last commit will improve the situation ?

**Comment by tuukkamustonen** [comment]
Yeah that commit tackles the issue well. Thanks!
