### ISSUE TITLE
Setup on Windows guide

### ISSUE THREAD

**Issue by FlYnN91** [vaab/gitchangelog#28]
Been trying to get this tool setup on Windows with no luck. Got Python 3.2 running, but the instructions just don't seem to be clear enough how to get going. Am I missing something? Clarification would be useful. Thanks

**Comment by vaab** [comment]
Yes, I've never tested under windows. I just did. It seems it'll need more love to work. The first issue with the code is that we are using subprocess.call and redirecting stdout and that fails. There might be numerous other incompatibilities. Sorry about that, but any PR going towards a full compatibility is welcome of course.

**Comment by FlYnN91** [comment]
Vaab, thanks for the reply. I really like the features of this tool. Shame Windows does not work. I tihink it may just give me a reason to delve into Python and see if I can help get it going on Windows.

**Comment by vaab** [comment]
You might want to join force with @Shirkit on issue #6, he seems to have gone through the first exceptions. I closed this issue, but I think having a version for windows is important, and I might join effort if you need help. Let's say that #6 is the main issue for windows compatibility. I shamelessly used your issue as a reminder that the documentation was misleading into thinking that there was an actual support under windows and I fixed it by only making it clear that wasn't the case.

I really have no experience in Windows, and I had even (small) troubles to install python, pip, gitchangelog and git on it, but this doesn't mean I won't be able to help, as there will probably be some change to be done on how some subpart of gitchangelog works (as it seems from the first exception).

So feel free to jump in, I'll be keeping track, and I'll help if you have specific issues (and I'm ready now for windows testing). 

If you don't do it, I'll probably try to tackle the issue myself, but I have no idea when. It could be in one year or in 3 months.

**Comment by vaab** [comment]
I'm happy to announce that version 3.0.0 that was just released is full compatible with windows (full tests, packaging)
