### ISSUE TITLE
Templates are extracted to invalid location and markdown template is missing

### ISSUE THREAD

**Issue by tuukkamustonen** [vaab/gitchangelog#34]
Running the latest 2.2.0, with `pystache` installed and `output_engine = mustache("markdown")` in my `.gitchangelog.rc`, running `gitchangelog` gives:

    Error: Invalid mustache template name 'markdown'.
    No available mustache templates found in '/home/musttu/.virtualenvs/foobar/python2.7/site-packages/templates/mustache'.

That directory does not exist at all. Instead, the templates are directly in virtualenv root:

    $ pip uninstall gitchangelog
    Uninstalling gitchangelog-2.2.0:
      /home/musttu/.virtualenvs/foobar/bin/gitchangelog
      /home/musttu/.virtualenvs/foobar/gitchangelog.rc.reference
      /home/musttu/.virtualenvs/foobar/lib/python2.7/site-packages/gitchangelog-2.2.0-py2.7.egg-info
      /home/musttu/.virtualenvs/foobar/lib/python2.7/site-packages/gitchangelog.py
      /home/musttu/.virtualenvs/foobar/lib/python2.7/site-packages/gitchangelog.pyc
      /home/musttu/.virtualenvs/foobar/templates/mako/octobercms-plugin.tpl
      /home/musttu/.virtualenvs/foobar/templates/mako/restructuredtext.tpl
      /home/musttu/.virtualenvs/foobar/templates/mustache/restructuredtext.tpl
    Proceed (y/n)?

And even in this case, `markdown.tpl` is missing.

It fails the same way without virtualenv (templates get extracted to `/usr/local/templates`, is it intentional?)

Some issues with installation scripts?

**Comment by vaab** [comment]
Many thanks for the feedback, can you tell me which version of ``pip`` and ``setuptools`` you are using ? Does all this works by forcing setuptools to version ``9.1`` ? or pip to ``1.5.6`` ? I'll do thorough test about this in the following days, I've been quite busy lately, and still am.

**Comment by tuukkamustonen** [comment]
The behavior is the same with pip 1.5.4 + setuptools 3.3 (from apt repos of Ubuntu 14.04 LTS) and with pip 7.0.3 + setuptools 17.1 (latest).

**Comment by vaab** [comment]
Ok, thanks, python packaging and including foreign files are a recurrent nightmare: they actually are put in different places depending if you use ``python setup.py install`` or ``pip install gitchangelog``. I had to resolve using a nasty hacks (that I was using on version 2.0.0). Can you tell me if last version works again for you ?

**Comment by tuukkamustonen** [comment]
Indeed, with 2.2.1 the templates now get extracted under `site-packages`.

BUT, it only works with pip 6.x and below - with pip 7.x the templates get again extracted to the virtualenv root. Apparently they changed something... there are number of backwards-incompatible changes, but can't see how any of them would affect this?

Markdown template is still missing from packaging, though, so I pushed #35.

The packaging is interesting indeed, `pip install` seems to always extract/install sdists (`.tar.gz`) while `python setup.py install` and `easy_install gitchangelog-2.2.1.tar.gz` compiled an egg and installed that, instead.

I also played around a bit with your project and packaging, couple of questions:

* Is it wise to use `d2to1` as it's kinda deprecated and abandoned?
* That `autogen.sh` script looks scary and running `python setup.py sdist` dirties the repository. Why not just use something like `setuptools-scm` (https://pypi.python.org/pypi/setuptools_scm/1.5.2) and hard-code the identifiers (`name`, `summary`, `modules`, etc.) into `setup.cfg` or `setup.py` files?

**Comment by tuukkamustonen** [comment]
There is this in pip 7.0.0:

> Build Wheels prior to installing from sdist, caching them in the pip cache directory to speed up subsequent installs. (PR #2618)

Installing with `pip install --no-use-wheel gitchangelog==2.2.1` avoids the wheel packaging and templates get extracted to correct place. So, it seems like gitchangelog would need to support wheel packaging as the new pip defaults to that!

**Comment by vaab** [comment]
I'm using the same python templates for managing my python project, and the current setup is shared between a number of python packages.

``d2to1`` is not meant to be deprecated AFAIK (last commit from the author about that dates of february of this year: https://bitbucket.org/pypa/setuptools/issue/343/unloading-of-setuptools-and-distutils-in#comment-15525751 ). And I'd personally rather use passive config and support these views by using it myself. However, there are some trailing bugs with >= setuptools 9.1 and python 2.7 that are still not corrected, and I'm aware that ``d2to1`` could be announced deprecated in near future.

The ``./autogen.sh`` only replaces values in ``setup.cfg`` and ``setup.py`` before launching all this (and generate the changelog). But I understand your concern. It was subject of concern some times ago, but seem here completely unrelated, and is used on ~15 repository for a few years without recent concerns. I'm not for release commits.

I didn't know about ``setuptools_scm``, but I need to change version in ``CHANGELOG.rst`` , or sometimes in docs, or in internal values in programs (for instance some packages includes ``__version__`` module attrs).

There are however some downsides as the fact it's puzzling for unsoiled souls ;)

Many thanks for spotting the ``--no-use-wheel`` option... it seems that python packagers have a never ending attraction for chaos. I'll look into it in the following days.

**Comment by tuukkamustonen** [comment]
Oh well, nice of you to explaining all that. Yeah, there are way too many approaches to packaging and building things in the python wonderland. And as you say, often what we have found reliable over trial-and-error is indeed better than the unknown and mysterious new kid on the block.

Not sure what you mean with "release commits" though, `setuptools-scm` does not require separate release commits as it relies on tags. It shouldn't prevent you from manually updating the versions in other files the same way (and you could even call `get_version()` directly in file if it's in python). Inside packages I tend to use `pkg_resources.get_distribution('gitchangelog').version` but then, I don't have to worry about legacy `distribute` and such :)

Anyway, sorry for going offtopic! I might actually take a look at this...

**Comment by tuukkamustonen** [comment]
Wheel [PEP](https://www.python.org/dev/peps/pep-0427/#the-data-directory) states:

> Any file that is not normally installed inside site-packages goes into the .data directory, named as the .dist-info directory but with the .data/ extension:
> 
> distribution-1.0.dist-info/
> 
> distribution-1.0.data/
> The .data directory contains subdirectories with the scripts, headers, documentation and so forth from the distribution. During installation the contents of these subdirectories are moved onto their destination paths.

The files listed in `data_files` are regarded as these files when wheel is built. If one wants normal files to reside inside `site-packages` and within the package's modules, one needs to use `package_data`.

It is also described here: https://packaging.python.org/en/latest/distributing.html#data-files

Thought it seems like `setuptools` does not even have the `data_files` option (does it just extend from the standard `distutils` then...?).

To me it actually sounds like the package was actually working as intended in `2.2.0` and is now actually broken in `2.2.1` so maybe your hack actually broke it? :) If one wants the templates files to reside next to `gitchangelog.py` and be thus discoverable by the code, one needs to use `package_data`.

I tried replacing `data_files` with `package_data` in `setup.cfg` but the problem is that the repository does not have a package, just `gitchangelog.py` in the root. So, I created a directory, put gitchangelog.py and templates in there, and declared the directory as a package - then it worked.

You could:

    mkdir scripts
    mv gitchangelog scripts
    mkdir gitchangelog
    touch gitchangelog/__init__.py
    mv gitchangelog.py gitchangelog
    mv templates gitchangelog

Edit `setup.cfg`:

    [files]
    packages =
        gitchangelog
    package_data =
        gitchangelog =
            gitchangelog.rc.reference
            templates/mustache/restructuredtext.tpl
            templates/mustache/markdown.tpl
            templates/mako/octobercms-plugin.tpl
            templates/mako/restructuredtext.tpl
    ...

Reflect these changes in build scripts etc.

This would also heal the worrying(?) behavior of dropping `templates` directory right into the root of `site-packages` (if some other package did the same, they would overwrite each other).

It's messy, what do you think?

**Comment by vaab** [comment]
Wow, thx for your run down. 
Actually I already went by ``package_data`` docs which seems the correct option to use rather than ``data_files``. However, the files where simply not deployed at all (in both mode: ``pip install gitchangelog`` and  ``python setup.py install``). Then I went by:

http://stackoverflow.com/questions/7522250/how-to-include-package-data-with-setuptools-distribute

And I chose to take this for granted and a valid explanation for why it wasn't working on my side, and, it would be the first quirk of packaging in python, so it seemed pretty credible.

Note that the file made with ``python setup.py sdist`` will contains all the files (even ``test/*``), and this seems to come from ``MANIFEST.in``. But why these files are not used when ``pip install dist/*.tar.gz`` ? It's unexpected to have big contents in the package that don't get copied automatically.

I thought of putting all in a directory and make it a package, but this would mean accepting that one-files python package can't have a way to send correctly files with them. I opted for hope, and decided to give it a last chance by looking how I managed this in 2.0.0 which used a standard ``setup.py``. I re-discovered my nasty and dangerous hack (evidence that I had already lost too much time long ago on the same issue) to make it work that proved still efficient.

I'm on your side about the ``templates`` directory right into the root of ``site-packages`` and feel very uneasy with this, to say the least. Obviously this should be avoided, but I first don't understand why the python file don't get it's own directory when installing from ``pip install gitchangelog``. I must point out that with ``python setup.py install``, the package correctly gets it's directory.

Could you share branch/PR with your proposal, so I can work on it and test it with various combination of tools ? I'm ready to merge a proposal that transform gitchangelog from one-file-package to normal directory-package, as long as it fixes our concerns (on past and current versions of setuptools/pip).

**Comment by tuukkamustonen** [comment]
Ok I opened a pr that has the discussed changes. It *should* work with

- `python setup.py install` (from git or extracted sdist)
- `python setup.py sdist`
- `python setup.py bdist_wheel`
- `pip install <sdist-or-wheel>`

Tested with:

- pip 1.5.4 + setuptools 3.3 
- pip 7.0.3 + setuptools 17.1

But, I am sure I missed something so give it a spin. I'm not familiar with `d2to1` and it seems to offer some abstractions, which I'm not sure are good thing or not...
