### ISSUE TITLE
Document default behavior

### ISSUE THREAD

**Issue by tuukkamustonen** [vaab/gitchangelog#37]
By default, gitchangelog makes sections under each version by builtin rules. At least following rules are followed:

- `new:` as "New"
- `chg:` as "Changes"
- `fix:` as "Fixes"

This behavior is not documented anywhere. The default sectioning can be overridden by custom config file and `section_regexps`. Still, however, documentation should describe the default behavior.

There is a sample configuration file, but that's different from telling what the defaults are.

Or is reference config used as defaults? The behavior seems a bit inconsistent:

- `section_regexps` are not completely replaced (prefixes are still snipped)
- `ignore_regexps` is

Did not try other params.

**Comment by vaab** [comment]
Yes, the reference config file is used as the default. Can you elaborate on what seem inconsistent, I'm ready to work on the documentation. I just didn't catch what was missing (about ``section_regexps``)...

**Comment by tuukkamustonen** [comment]
@vaab: Consider the following config:

    section_regexps = [
        ('', None)
    ]

This disables the sectioning under versions (no more "New", "Fixed" and "Changes" sections that come per default).

However, gitchangelog still strips the new:/fix:/chg: prefixes from the log entries. This is specified in the reference configuration file (https://github.com/vaab/gitchangelog/blob/master/gitchangelog.rc.reference#L77). Having a commit with message of:

    New: test commit

Produces a changelog of:

    - test commit. [Tuukka Mustonen]

"New" was snipped away, even though I didn't instruct so in my custom `section_regexps` config.

**Comment by tuukkamustonen** [comment]
Oh well, nevermind, just found `subject_process`. And I accidentally thought that regexps were specifying the replacing operation that snips the prefixes away. Stupid me.

So yeah, reference file is inherited as defaults, that can be overridden.

Nothing wrong here, I should just RTFM.

**Comment by vaab** [comment]
Well, if you have suggestion about a place to add a note or a sentence that would have avoided you to fall in this trap, I would be grateful. I might wish to add it to the documentation of others.

For instance, I could clearly state in the comment documentation of ``gitchangelog.rc.reference``, above ``section_regexp``, that these are only classifying regexp and that they won't touch the actual summary that will get printed, so the user might want to look also at ``subject_process`` if the subject needs some changes.

**Comment by tuukkamustonen** [comment]
Opened https://github.com/vaab/gitchangelog/pull/40 to point out where the defaults come from.
