### ISSUE TITLE
need to get change log between 2 tags 

### ISSUE THREAD

**Issue by aomaryus** [vaab/gitchangelog#38]
something like:
gitchangelog most_recent_tag tag_from_last_deployment

**Comment by vaab** [comment]
Hi, this is a wanted request and is called "incremental changelog", the thread #26 is tracking the actual developpement (or ideas) around this issue. Feel free to participate if you feel with missed something.

**Comment by vaab** [comment]
I'll close this thread as discussion is happening on #26 and you might want to know that pull request has been proposed with the feature you asked. You might want to help test it.
