### ISSUE TITLE
Installation with pip 7.0+ is broken

### ISSUE THREAD

**Issue by tuukkamustonen** [vaab/gitchangelog#41]
While `pip install gitchangelog` works just ok, when invoking `gitchangelog`, it does not find the reference config file. I do have local `.gitchangelog.rc` file, but I get:

```
Traceback (most recent call last):
  File "/home/musttu/Code/virtualenvs/citrus/bin/gitchangelog", line 11, in <module>
    sys.exit(main())
  File "/home/musttu/Code/virtualenvs/citrus/local/lib/python2.7/site-packages/gitchangelog.py", line 1028, in main
    section_regexps=config['section_regexps'],
KeyError: 'section_regexps'
```

I don't specify `section_regexps` in my config file, so it's not found from config.

On pip 6.x, `gitchangelog.rc.reference` extracts to:

```
~/.virtualenvs/citrus/lib/python2.7/site-packages/gitchangelog.rc.reference
```

On pip 7.x, it extracts to:

```
~/.virtualenvs/citrus/gitchangelog.rc.reference
```

@ vaab: Would you consider checking https://github.com/vaab/gitchangelog/pull/36 that might also fix this. It's somewhat old now, so I'm not sure.

**Comment by vaab** [comment]
I'm sorry, I have very little time right now, and I must admit that packaging issues are time consuming. I have noticed #36, and I'm still undecided about making ``gitchangelog`` a full package... I know that a lot of people appreciate single files project. Of course, there's a limit to this concept, but I'm not sure ``gitchangelog`` has grown enough to be considered eligible for being upgraded to a full package.

I really am dreading these packaging issues that are a plague to python ecosystem (take a look at ``.travis.yml``: I'm testing the packaging system, but had to force some versions). I'm aware that the fact of being a single file package puts this project on a bad start, so this is why we'll probably move toward your solution in the end.

I dislike the idea of being forced into a move by the packaging system flaws. But the current state of ``gitchangelog`` installability is not acceptable neither.

Please, feel free to share your thoughts on this topic, and bare with my very slow time of decision on this matter.

**Comment by nhomar** [comment]
Hello.

I think it is almost mandatory an element as col as this being managed properly as a package.

Even I can recommend use this **way:

https://jeffknupp.com/blog/2013/08/16/open-sourcing-a-python-project-the-right-way/

I love the way it is explained and maybe this package can be simply a dependency template for things like cookiecutter templates.

https://github.com/audreyr/cookiecutter

One of the leaks of such package templates (which is awesome BTW) is a proper automated changelog management (and by far your work is excellent and in my opinion is a proper tool to use with).

It is related also to your idea here https://github.com/vaab/gitchangelog/issues/39 and here https://github.com/vaab/gitchangelog/issues/32 to be considered completed.

A better config setting and parameter management with [**Python](http://click.pocoo.org/5/) Click which convert it in a complete cli interface and almost magically will help.

It means I fell like your work can be easily included in the set of **standars ways to manage a proper python /whatever project, for that be packaged properly is a MUST not a SHOULD.

My 2 cents... EXCELLENT work here.
