### ISSUE TITLE
UnicodeDecodeError: 'ascii'  when running gitchangelog

### ISSUE THREAD

**Issue by osroflo** [vaab/gitchangelog#50]
Hi, I've used gitchangelog for a couple months in our development process. Everything was working great. But  when I was trying to generate the changelog (in on of our many repositories), I get this error: 
```
gitchangelog

Traceback (most recent call last):
  File "../gitchangelog/gitchangelog", line 1052, in <module>
    main()
  File "../gitchangelog/gitchangelog", line 1034, in main
    subject_process=config.get("subject_process", noop),
  File "../gitchangelog/gitchangelog", line 882, in changelog
    for commit in commits:
  File "../gitchangelog/gitchangelog", line 644, in log
    for key in GIT_FORMAT_KEYS]))
  File "../gitchangelog/gitchangelog", line 270, in <lambda>
    @itermap(lambda r: r.decode(_preferred_encoding))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 24: ordinal not in range(128)
```

I checked the commit messages using git log:
```
git log > logs.txt
```

looks like there is one commit message with a  zero-width space character <200b>. If I open the file in vim:

```
vi logs.txt

commit 5010274e14641e0891c0844318774741b5864947
Author: osroflo 
Date:   Tue Mar 29 10:31:39 2016 -0700

    API Enhancements*<200b>
    - Added Elasticsearch search() function to our Query library
    - Moved construction of response parameters out of controller and into Response Formatter library
    - Return a status of fail if something goes wrong with returning our API response instead of always returning status of success
```

Is there a way that I can fix this?

NOTE:
- We are using jenkins to generate logs automatically.

**Comment by osroflo** [comment]
I realized that if I ssh to jenkins and run gitchangelog manually, everything works great. The only problem is when jenkins runs the job through the UI. I fixed the Unicode error setting this in the Execute Shell textarea:
```
export PYTHONIOENCODING=UTF-8
export LC_CTYPE=en_US.UTF-8
```

I found the solution here: 
http://stackoverflow.com/questions/6076203/how-do-you-set-the-default-encoding-in-jenkins

**Comment by kmturley** [comment]
Another solution is to use Python 3

```
brew update
brew install pyenv
pyenv install 3.7.3
pyenv local 3.7.3
make virtualenv
```
