### ISSUE TITLE
No output after gitchangelog

### ISSUE THREAD

**Issue by drxos** [vaab/gitchangelog#52]
Hello.
### situation.

The  command ..

``` sh
echo $GITCHANGELOG_CONFIG_FILENAME
```

gave me 

``` sh
/home/drxos/.gitchangelog.rc
```

and this file is a perfect copy of the sample you suggested.

``` sh
git log  - -oneline
```

gave this : 

```
f9432cd chg: dev: cofigurations !cosmetics
7b2884c chg: dev: initial commit !cosmetics
68bd063 new: dev: initial commit !minor
```

Unfortunetly, 

``` sh
gitchangelog
```

output no thing.

Where is the mistake ?

**Comment by vaab** [comment]
No tags ? Anyway, gitchangelog should probably output something on errorlevel on this case... I'll look into this later. Tell me if adding a tag helps.

**Comment by drxos** [comment]
Adding a tag helps very much. See you then @vaab .

**Comment by vaab** [comment]
Oups, I need to keep this open, as I'd like to have a nice reminder to output some error message and probably an errorlevel, and why not a short notice in the documentation.

**Comment by drxos** [comment]
Great! Even when I am not so good in Regex, I cannot help you. Your project is very useful for pythonist. Thus don't give up.
