### ISSUE TITLE
Feature request: View Changes per tag

### ISSUE THREAD

**Issue by kashif619** [vaab/gitchangelog#53]
It would be nice if we can filter CHANGELOG per tag

something like

$~ gitchangelog --tag 1.0.5
OR
$~ gitchangelog 1.0.5
(Should display only 1.0.5 tag changes)

**Comment by vaab** [comment]
Please check #26 and tell me if this previous request would fill your use case. If you are not sure or require some additionnal information in the description given in #26, feel free to comment with your question or remarks.
