### ISSUE TITLE
Unreleased Version

### ISSUE THREAD

**Issue by maarek** [vaab/gitchangelog#55]
Where do you specify the %%version%% for unreleased version that's in the rc file?

Also on another note: How do you go about exporting the respond from gitchangelog to a file? Do you have a process around this built in or do you manage it by hand?

**Comment by vaab** [comment]
> Where do you specify the %%version%% for unreleased version that's in the rc file?

Yes, it is in the rc file.

> Also on another note: How do you go about exporting the respond from gitchangelog to a file? Do you 
> have a process around this built in or do you manage it by hand?

I'm using shell redirection, for instance:

    gitchangelog > ChangeLog

**Comment by maarek** [comment]
I'm actually doing a sed replacement on %%version%% on the changelog instead of having to change it in the rc file every time. 

That is also what I was thinking and pretty easy to throw into a script. I just wasn't sure if the app itself output the changelog into a file automatically and just wasn't working.

On another note and maybe another issue, I'm having issues with the audience tag. If I include it then the commit does not show up in the log, it doesn't generate the action section either. If I leave it off then it it works as expected. Thoughts?

**Comment by vaab** [comment]
> I'm actually doing a sed replacement on %%version%% on the changelog instead of having to change it in the rc file every time.

That's exactly how it is meant to be. ``gitchangelog`` is actually doing this for itself (check ``autogen.sh``).

For your issue with audience tag, you should bake a quick example so I can help you (and in a separate thread if possible). If this doesn't work as expected it is a bug that I should tackle.
