### ISSUE TITLE
Can't run under Windows

### ISSUE THREAD

**Issue by Shirkit** [vaab/gitchangelog#6]
I can't currently run this under Windows.
- close_fds can't be set to True while redirecting the other outputs
- ';'  doesn't work as multi launch on the same line, '&' does

Even after those fixes, something over here (https://github.com/securactive/gitchangelog/blob/master/gitchangelog.py#L297) crashes everything and I wasn't able to solve it.

**Comment by vaab** [comment]
@Shirkit could you send a git ref to the code you've already written ?, even if it is on an older version of ``gitchangelog``.

I have very little experience of windows, and I'm interested in how you managed to get through the first exceptions. If you can't I'll find how on my own, I just wanted to avoid loosing too much time on these.

Many thanks.

**Comment by vaab** [comment]
With the recent developpement I decided to include the full windows support in next release 3.0.0 ... More work is needed to include windows testing and documentation before inclusion. But if you need windows compatibility, #42 and #43 are providing working fixes.

**Comment by vaab** [comment]
FYI, the last version of gitchangelog is now compatible with windows thanks to this #68 .
