### ISSUE TITLE
Use annotated tag date instead of commit date when available

### ISSUE THREAD

**Issue by toninlg** [vaab/gitchangelog#60]
Hi,

I use annotated tag to number version of my code. Changelog is displayed properly, but I've just seen that the date displayed next to the tag in the log is the date of the commit that is tagged whereas I would expect to have the date of the tag itself displayed (I tag the commit when I plan to release).
Can this be configured?

Thank you,
Antoine.

**Comment by vaab** [comment]
No, and that seems a totally legit feature. I'd propose that ``gitchangelog`` could probe which type of tag it is and use per default the date of the annotated tag if it is an annotated tag, and the tag of the commit otherwise.

**Comment by toninlg** [comment]
Sounds good to me.

Thank you.

**Comment by vaab** [comment]
Thanks for you suggestion, it was added to master branch and should be part of the upcoming ``3.0.0`` release.

**Comment by vaab** [comment]
I'm happy to announce that version 3.0.0 that was just released includes this change.
