### ISSUE TITLE
Only use the commit subject in the changelog.

### ISSUE THREAD

**Issue by skorokithakis** [vaab/gitchangelog#65]
It looks like gitchangelog uses the entire commit in the changelog. However, this is rather heavy and leads to cumbersome changelogs. The commit subject (the first line) should be describing the commit at a high level, with the rest of the commit message being lower-level details. For example, see here:

```
Fixes
~~~~~

- Abort with an error if the bulb closes the connection (fixes #5).
  [Stavros Korokithakis]

- Flow API improvements (#3) [Teemu R]

  * Flow API improvements

  1. Cast brightness always to int.
  2. Raise an exception when supplied with more than maximum amount of transitions.
  3. Supply repr dunders.

  * Flow: use warning instead of exception for invalid values. Add check for brightness' validity.

  * Change warning to display for over 9 messages.

  * Silently clamp brightness to 100, as elsewhere.
```

This is a side-effect of the merging process, and is rather ugly in this case, but it generally seems to me that only the first line should be included. That would make the changelog much prettier (assuming I had taken care to write proper commit messages, which is a sound assumption).

**Comment by vaab** [comment]
Hi, thanks for your interests in ``gitchangelog``. A lot of people are using the body of the commit to get a little more in their changelogs. What I might suggest you is to make your own template (mako and mustache examples templates are included for you to hack, just remove the body part). You could also use the ``gitchangelog.rc`` to set ``body_process`` to ``lambda txt: ""``.

Configurability of ``gitchangelog`` allows you to make your own changelog as it suits you with little changes.

For now, the default format suits my need, and I believe it suits the needs of a majority. I may be wrong, but I don't feel your requests represents a majority.

For merging, either users of ``gitchangelog`` won't include the commit at all (with ``include_merge = False``, or they are carefull about their body content.

**Comment by skorokithakis** [comment]
Ah, thank you, that lambda is exactly what I want. May I suggest making it a bit clearer in the docs that `body_process` does not apply to the first line? I didn't use it because I thought it applied to the entire commit message (including the first line). Otherwise, it's perfect, thank you!
