### ISSUE TITLE
use "git tag" for marking a release

### ISSUE THREAD

**Issue by gthieleb** [vaab/gitchangelog#72]
I am using tags for marking releases:

	$ git tag
	v1.0
	v1.1
	v1.1.2
	v1.1.3

My expectation is that gitchangelog would use tags as releases headers and prints the commit between tags. 

But currently only one release header unreleased is created:

	Changelog
	=========

	%%version%% (unreleased)
	------------------------
	- Bump version. [Max Muster]
	- Use KeyValueMetadata.update in view. [Max Muster]

	  - KeyValueMetadata._load_original() to load original content and try to
	    keep original field ordering
	  - some list comprehension magic in KeyValueMetadata.update to keep the
	    ordering

**Comment by vaab** [comment]
Thank you for your interest, please configure ``tag_filter_regexp``. A lot of project have different opinion on various matter. Gitchangelog is configurable.

https://github.com/vaab/gitchangelog/blob/master/src/gitchangelog/gitchangelog.rc.reference#L148

**Comment by gthieleb** [comment]
Works delightful when regex ist changed:

    tag_filter_regexp = r'^v[0-9]+\.[0-9]+(\.[0-9]+)?$'
