### ISSUE TITLE
Configurable Template Path

### ISSUE THREAD

**Issue by gthieleb** [vaab/gitchangelog#73]
Template path should be independent of the package path best configurable via ~/.gitconfig

    [gitchangelog]
    rc-path = ~/.gitchangelog/gitchangelog.rc
    template-path = ~/.gitchangelog/templates

**Comment by vaab** [comment]
Hi, thanks for your interest in ``gitchangelog`` and your suggestion.

I'm releasing soon a new version (you can have a peak of it in branch rc1). There are massive evolutions, and one of them is the ability to directly specify a file name in the configuration file:

    output_engine = mustache(".gitchangelog/templates/mytemplate.tpl")

The path is relative to the root dir of the git repository, but you can specify absolute path.

I'm keeping this issue open, has I think this is a good additional idea and I wish to implement it.
