### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by andreroggeri** [vaab/gitchangelog#74]
I saw many issues and PRs reported regarding Windows support.

From my understanding this tool **doesn't** work on Windows yet. Am I right ?

**Comment by vaab** [comment]
I'm finalizing the version 3.0.0 which does support 100% windows. You can try the master version. Until 3.0.0 is not released I don't want to close any issues related.

**Comment by andreroggeri** [comment]
Good to know and great job btw.

I'll try the master version tomorrow and report here.

**Comment by vaab** [comment]
Thanks for your support. The version 3.0.0 is released and supports windows. Comments and tests, feedbacks are always greatly appreciated.
