### ISSUE TITLE
changelog generation fails when commit message is empty

### ISSUE THREAD

**Issue by topic2k** [vaab/gitchangelog#76]
I've tried to build a changelog for a project. From the repo root i called `gitchangelog` (no configuration file) and get this exception:
```python
Error: Exception while running 'gitchangelog':
  | Traceback (most recent call last):
  |   File "c:\python27sl\lib\site-packages\gitchangelog\gitchangelog.py", line 1958, in main
  |     log_encoding=log_encoding,
  |   File "c:\python27sl\lib\site-packages\gitchangelog\gitchangelog.py", line 1644, in changelog
  |     first_version = next(versions)
  |   File "c:\python27sl\lib\site-packages\gitchangelog\gitchangelog.py", line 1595, in versions_data_iter
  |     "subject": subject_process(commit.subject),
  |   File "c:\python27sl\lib\site-packages\gitchangelog\gitchangelog.py", line 374, in __call__
  |     return self.fun(text)
  |   File "c:\python27sl\lib\site-packages\gitchangelog\gitchangelog.py", line 378, in <lambda>
  |     return TextProc(lambda text: value.fun(self.fun(text)))
  |   File "c:\python27sl\lib\site-packages\gitchangelog\gitchangelog.py", line 378, in <lambda>
  |     return TextProc(lambda text: value.fun(self.fun(text)))
  |   File "c:\python27sl\lib\site-packages\gitchangelog\gitchangelog.py", line 390, in ucfirst
  |     return msg[0].upper() + msg[1:]
  | IndexError: string index out of range
```

gitchangelog 3.0.0
python 2.7.12
project: [EventGhost](https://github.com/EventGhost/EventGhost)
problematic commit: [51f0590d366318104e55c2be4cb3c179bf57a8f3](https://github.com/EventGhost/EventGhost/commit/51f0590d366318104e55c2be4cb3c179bf57a8f3)

**Comment by vaab** [comment]
Thanks for your report. The bug should be corrected.
Please note that the main ``gitchangelog.rc.reference`` changed to ignore these empty commits, but if you wish to add them, there's a new formatting directive in ``subject_process`` that checks for empty subject to decide what message should be displayed in the changelog.
