### ISSUE TITLE
How to use asciidoc as output_engine ?

### ISSUE THREAD

**Issue by IbnSaeed** [vaab/gitchangelog#82]
Hello

I would like to know the following is the correct way to add the outputengine to [asciidoc](http://asciidoctor.org/docs/what-is-asciidoc/)

output_engine = mustache("asciidoc")

Is it correct ?

**Comment by vaab** [comment]
Well, do you understand that you'll need to provide a template with the name "asciidoc" ? I suggest that you start from the mustache template for markdown format for instance. If you can provide me with the given template, I'll gladly integrate it in gitchangelog release.

If things are unclear for you, try to give me a few points to clarify. If you don't really know what to ask me, then tell me what you understood about the templating system and how to use it to achieve what you need. I'll hook to that and will try to complete the documentation of gitchangelog with what we come up with in this thread.
