### ISSUE TITLE
Customize author output

### ISSUE THREAD

**Issue by argaen** [vaab/gitchangelog#85]
I haven't seen any way in the docs on how to customize how author is displayed in the release notes.

Right now it is appended to the end of the body like `[author]`. I would like to apply regexp modifications to customize how to display it. My use case is to make it point to the github profile page.

**Comment by vaab** [comment]
Templating offers you full control, with mako template you should have full python facility. I can help you on that if you give me a full spec of what you'd like (with an example of the source code you'd like).

**Comment by argaen** [comment]
Oh, I'll have a look at the templates thanks! 

Basically the idea would be to transform `[author]` to `[author](https://github.com/author)`.

**Comment by argaen** [comment]
Got it :). Thanks!

**Comment by karbassi** [comment]
@argaen can you post your solution?

**Comment by argaen** [comment]
@karbassi

https://github.com/argaen/aiocache/blob/master/.release_notes.tpl
https://github.com/argaen/aiocache/blob/master/.gitchangelog.rc#L198

I didn't what I wanted at first because the author of the commits is not always the same name as you have in github, but with those templates you can customize most of the things :)
