### ISSUE TITLE
Tag Regexp seems to be not working

### ISSUE THREAD

**Issue by ganglio33** [vaab/gitchangelog#91]
I tried to copy exactly your example. I use your standard config file and everything, with no changes. But release versions will not work. I.E. I will get everything as unreleased instead of release 1.0.1:

```
Changelog
=========


(unreleased)
------------

New
~~~
- Added new changelog feature (1.0.1) [ganglio]

Fix
~~~
- ToDo list tried to fix. [ganglio]

Other
~~~~~
- Added exceptions of analyzed horizon. [ganglio]
- Reinstalled CORS in app.py and added exception handler. [ganglio]
```

What did I do wrong/ do I have to change? Sorry for my beginners question.

**Comment by vaab** [comment]
Sorry for my late answer. Can you provide your list of tags ``git tag -l``, and your ``tag_filter_regex``

https://github.com/vaab/gitchangelog/blob/master/src/gitchangelog/gitchangelog.rc.reference#L153

If ever you felt that this was not clear, I would be interested to have your suggestion to where I should document that so that next user won't fall into the same problem you've experienced.

**Comment by ganglio33** [comment]
No worries. I did leave the tag_filter_regex as is in the rc file:

```
## ``tag_filter_regexp`` is a regexp
##
## Tags that will be used for the changelog must match this regexp.
##
tag_filter_regexp = r'[0-9]+\.[0-9]+(\.[0-9]+)?'
```
the tags git tag -l are the following:

v1.0.2
v2.0.1

But do I understand it correctly that the version has to be in a tag or is it sufficient to have it in the commit message (this is what I understand from the readme) ?

**Comment by ganglio33** [comment]
Ok with your comment and the hints in https://github.com/vaab/gitchangelog/issues/96
I arrived at the following modification to accept tags with a "v" before the number: 
`tag_filter_regexp = r'v+[0-9]+\.[0-9]+(\.[0-9]+)?'`

It works now. Thanks!

Maybe we could expand the readme to specify that the tags have to be added. As it stands I understood from the readme that you have to add the tag in the format (1.0.2) to the **commit message** (which I did to no effect).
