### ISSUE TITLE
Modifying markdown template - include commit hash

### ISSUE THREAD

**Issue by SamaraIT** [vaab/gitchangelog#97]
Hi,

I'm customizing template file (`markdown.tpl`) and I would like to include commit hash.  

I can use `{{{commit}}}` but it displays too much data that is not needed:  
`<GitCommit 'cf22f3eb566f35d42830630fdd0dbbebdb2baf81'>`   
I would like to get only hash part: `cf22f3eb566f35d42830630fdd0dbbebdb2baf81`

Can you please advice how to do that?

**Comment by vaab** [comment]
That's expected. What you see the ``repr()`` of the python object. You should use ``{{commit.sha1}}`` or ``{{commit.sha1_short}}`` to get what you need.

Tell me if this solved your issue.

**Comment by SamaraIT** [comment]
Yes, tnx
